apiVersion: v1
kind: Route
metadata:
  labels:
    f5type: altemista
  name: starter-java
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: moneytracker
    weight: 100